name: CIFuzz

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  CIFuzz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake clang pkg-config

      - name: Run CIFuzz
        uses: google/oss-fuzz/infra/cifuzz/actions/run-cifuzz@master
        with:
          oss-fuzz-project-name: 'sqlite'
          fuzz-seconds: 600
          dry-run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

